#!/bin/sh

echo '== Installing dependencies =='
gem install bundler --conservative
bundle check || bundle install

echo '== Removing old logs and tempfiles =='
rm -rf ./tmp/pids/*

echo '== Create database =='
bundle exec rake db:setup

echo '== Starting application server =='
bundle exec puma -C config/puma.rb